language: java
jdk:
 - openjdk8
 - openjdk11
notifications:
  email:
    recipients:
      - nathanthomspson@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
